/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data.mining;

import java.util.List;
import java.util.Set;
import javax.swing.JPanel;
import data.mining.APriori;
import java.util.ArrayList;

/**
 *
 * @author tdvdev
 */
public class Main extends javax.swing.JFrame {
//    private JPanel pnlMainPanel;
    private int optionInput;
    private String linkInput;
    private List<Set<String>> itemsetList;
    private APriori<String> serviceImpl;

    /**
     * Creates new form Main
     */

    public Main() {
        optionInput = 1;
        linkInput = "";
        itemsetList = new ArrayList<>();
        serviceImpl = new APriori<String>();
        initComponents();
        setDefaultLookAndFeelDecorated(true);
        setLocationRelativeTo(null);
        //Set cho giao điện đầu tiên là main bảng công việc
        HomePanel pnlHomePanel = new HomePanel();
        pnlMain.add(pnlHomePanel);
    }

    public int getOptionInput() {
        return optionInput;
    }

    public void setOptionInput(int optionInput) {
        this.optionInput = optionInput;
    }

    public String getLinkInput() {
        return linkInput;
    }

    public void setLinkInput(String linkInput) {
        this.linkInput = linkInput;
    }

    public List<Set<String>> getItemsetList() {
        return itemsetList;
    }

    public void setItemsetList(List<Set<String>> itemsetList) {
        this.itemsetList = itemsetList;
    }

    public APriori<String> getServiceImpl() {
        return serviceImpl;
    }

    public void setServiceImpl(APriori<String> serviceImpl) {
        this.serviceImpl = serviceImpl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        menuMain = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuOption = new javax.swing.JMenu();
        menuOptionMinsup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setLayout(new java.awt.GridBagLayout());

        menuFile.setText("File");

        menuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuOpen.setText("Open File");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuOpen);

        menuMain.add(menuFile);

        menuOption.setText("Option");

        menuOptionMinsup.setText("Minsup");
        menuOption.add(menuOptionMinsup);

        menuMain.add(menuOption);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenu menuOption;
    private javax.swing.JMenuItem menuOptionMinsup;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
